include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = BadgeForgePrefs
BadgeForgePrefs_FILES = BFRootListController.m
BadgeForgePrefs_FRAMEWORKS = UIKit
BadgeForgePrefs_PRIVATE_FRAMEWORKS = Preferences
BadgeForgePrefs_INSTALL_PATH = /Library/PreferenceBundles
BadgeForgePrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
